"""对外暴露能力层的目录、协议、绑定、调用器与运行时接口。"""

from .adapters import (
    ADAPTERS,
    CapabilityAdapter,
    DirectModelCapabilityAdapter,
    HttpApiCapabilityAdapter,
    InternalToolCapabilityAdapter,
    McpServerCapabilityAdapter,
    WorkflowApiCapabilityAdapter,
    build_adapter_manifest,
    resolve_capability_adapter,
)
from .bindings import (
    BINDING_TYPES,
    binding_prompt_view,
    get_capability_bindings,
    get_capability_bindings_for_capability,
    merge_capability_bindings,
    normalize_capability_binding,
    resolve_capability_binding,
)
from .invoker import (
    build_capability_invoke_prompt,
    build_requested_capability_execution,
    extract_capability_invocations,
    extract_capability_invocations_from_text,
)
from .protocol import (
    PROTOCOL_VERSION,
    CapabilityBindingSpec,
    CapabilityContract,
    CapabilityInvocationRequest,
    CapabilityInvocationSpec,
    build_binding_spec,
    build_capability_contract,
    build_invocation_request,
    build_invocation_spec,
    summarize_contract,
)
from .registry import (
    DEFAULT_CAPABILITY_CATALOG,
    DEFAULT_CAPABILITY_SETTINGS,
    capability_prompt_view,
    default_capabilities_for_stage,
    get_default_capability_catalog,
    get_capability_catalog,
    get_capability_index,
    merge_capability_settings,
)
from .runtime import CapabilityApplyResult, CapabilityExecutionContext, CapabilityRuntime

__all__ = [
    "ADAPTERS",
    "BINDING_TYPES",
    "PROTOCOL_VERSION",
    "CapabilityAdapter",
    "CapabilityApplyResult",
    "CapabilityBindingSpec",
    "CapabilityContract",
    "CapabilityExecutionContext",
    "CapabilityInvocationRequest",
    "CapabilityInvocationSpec",
    "CapabilityRuntime",
    "DEFAULT_CAPABILITY_CATALOG",
    "DEFAULT_CAPABILITY_SETTINGS",
    "DirectModelCapabilityAdapter",
    "HttpApiCapabilityAdapter",
    "InternalToolCapabilityAdapter",
    "McpServerCapabilityAdapter",
    "WorkflowApiCapabilityAdapter",
    "binding_prompt_view",
    "build_adapter_manifest",
    "build_binding_spec",
    "build_capability_contract",
    "build_capability_invoke_prompt",
    "build_invocation_request",
    "build_invocation_spec",
    "build_requested_capability_execution",
    "capability_prompt_view",
    "default_capabilities_for_stage",
    "extract_capability_invocations",
    "extract_capability_invocations_from_text",
    "get_capability_bindings",
    "get_capability_bindings_for_capability",
    "get_default_capability_catalog",
    "get_capability_catalog",
    "get_capability_index",
    "merge_capability_bindings",
    "merge_capability_settings",
    "normalize_capability_binding",
    "resolve_capability_adapter",
    "resolve_capability_binding",
    "summarize_contract",
]
